### ISSUE TITLE
Develop a tool to load OWL files to a SPARQL endpoint

### ISSUE THREAD

**Issue by melaasar** [opencaesar/owl-tools#1]
## User Story
As a developer, I would like to implement a tool to load OWL files to a SPARQL endpoint so that I can query the data.

## Detailed Description
Given a catalog of OWL files, and a SPARQL endpoint URL, we want to find all the OWL files and load them to the endpoint.
Jena Java API for endpoint is: https://jena.apache.org/documentation/rdfconnection/

One dataset contains a collection of OWL files and has a name.

## Acceptance Criteria
- [x] Given a OWL catalog, and a dataset name, you can invoke the CLI to upload it to an SPARQL endpoint with the given name, e.g., owl-load -i path/to-/owl/catalog -n dataset-name -e sparql-endpoint

## Sub-task List
- [x] Collect all the OWL files from the catalog
- [x] Establish connection with SPARQL endpoint
- [ ] Create a dataset with the given name
- [x] Load the owl files to the dataset
- [x] Commit the dataset

**Comment by truongdavid98** [comment]
To deploy Fuseki as a web app, you must use servlet 3.1 API (Tomcat 8+). Tomcat 7 and Jetty 8 will lead to an HTTP Exception 500.

**Comment by truongdavid98** [comment]
To my understanding, the dataset must exist prior to loading the data. I do not think you can create a dataset via Jena API.

**Comment by melaasar** [comment]
Done with PR #3
