### ISSUE TITLE
Update Owl-Query

### ISSUE THREAD

**Issue by truongdavid98** [opencaesar/owl-tools#12]
## User Story
As a user, I would like owl-query to be able to accept a directory of queries so that a single instance of owl-query can execute all the query files in the directory.

## Detailed Description
Given a folder as the query filepath arg, execute all the .sparql files and store the results in the result path. 

## Acceptance Criteria
- [ ] Given a directory then return a set of frames matching all the .sparql files
- [ ] Given a file return a singular framing matching that .sparql file
- [ ] Given an invalid path, return an error 
- [ ] Given a directory with no .sparql files, give the user a warning 

## Sub-task List
- [ ] Update command line to accept directories
- [ ] Validate the given argument
- [ ] Find all the .sparql files and execute them in parallel
