### ISSUE TITLE
Develop a tool to query a SPARQL endpoint

### ISSUE THREAD

**Issue by truongdavid98** [opencaesar/owl-tools#3]
## User Story
As a developer, I would like to implement a tool to query a SPARQL endpoint so that I can save the result of the query locally.

## Detailed Description
Given a SPARQL endpoint URL, a query file, a path to place the result, and optionally a desired result format, we want to write the result to a file of the name queryFile.frame in the designated result directory. 

## Acceptance Criteria
- [x] Given a SPARQL endpoint URL, a query file, a path to place the result, and optionally a desired result format, invoking the CLI will create a result file (with the name queryFile.frame) inside of the desired result directory. E.g.    
owl-query -e http://sparqlEndPoint/db -q path/to/queryFile -r path/to/result -f xml (default)

## Sub-task List
- [x] Create Query from File
- [x] Establish connection to SPARQL endpoint
- [x] Execute query at endpoint
- [x] Output result to XML (default)
- [x] Output to different formats

**Comment by melaasar** [comment]
Fixed by #4
