### ISSUE TITLE
develop gradle plugins

### ISSUE THREAD

**Issue by truongdavid98** [opencaesar/owl-tools#6]
## User Story
As a developer, I would like gradle plugins for the Owl Tools so that they can be invoked from a gradle build.

## Detailed Description
Create gradle plugins for Owl-Load and Owl-Query so that they can be invoked in the DocBook Adapter gradle build. 

## Acceptance Criteria
- [x] Able to execute Owl-Load via the gradle plugin interface
- [x] Able to execute Owl-Query via the gradle plugin interface
- [x] Execute both from a gradle build file

## Sub-task List
- [x] Turn Owl-Load into a Gradle Plugin
- [x] Turn Owl_Query into a Gradle Plugin

**Comment by melaasar** [comment]
Done with commits #5 and #4
